project:
  type: website

website:
  title: "Hattie King"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: My_Resume.pdf
        text: Resume

format:
  html:
    theme: lumen
    css: styles.css
    toc: false



